### ISSUE TITLE
NGINX integration? 

### ISSUE THREAD

**Issue by scramatte** [sannremy/PHP-Push-WebSocket#13]
Hi,

I'm trying to setup your example through NGINX proxy with or without SSL.
But I'm unable to get it working.   When I access the websocket server directly it works perfectly.

Thank you
Regards

**Comment by srchea** [comment]
Hi, sorry I've never tried with nginx proxy, I have used php-fpm with nginx.
Maybe, the nginx proxy configuration should have headers to forward websocket requests.
https://www.nginx.com/blog/websocket-nginx/
