### ISSUE TITLE
Windows 10 Pro composer install error

### ISSUE THREAD

**Issue by stefanache** [sannremy/PHP-Push-WebSocket#14]
Hello,

I have tried this command
&nbsp;<b>composer require "srchea/php-push-web-socket"</b>

and given this error
&nbsp;<i>Root package 'srchea/php-push-web-socket' cannot require itself in its composer.json
&nbsp;Did you accidentally name your root package after an external package?</i>

Remark: and with composer install given same error!

Thanks for support.

**Comment by srchea** [comment]
Hi, you have to call `composer require srchea/php-push-web-socket` in a project folder, not from this repository (I assumed).

**Comment by stefanache** [comment]
yes from folder I doned
