### ISSUE TITLE
I have "The client doesn't support WebSocket"

### ISSUE THREAD

**Issue by hienngong** [sannremy/PHP-Push-WebSocket#15]
Please give me some advances to solve this issue? I use Chrome version 64 on client, web server by xampp v3.1 on Win10. 
 
![image](https://user-images.githubusercontent.com/36908874/36768924-f79a0152-1c73-11e8-82eb-4d9d0cfcb1ce.png)

**Comment by davidutzus** [comment]
I solved this problem by changing flags for socket_recv on line 248 from "MSG_DONTWAIT" to "MSG_WAITALL". 
Now looks like:

```php
while ($bytes = @socket_recv($socket, $r_data, 2048, MSG_WAITALL)) {
    $data .= $r_data;
}
```
