### ISSUE TITLE
Is it possible that you do not use `pcntl_fork` and use else?

### ISSUE THREAD

**Issue by NabiKAZ** [sannremy/PHP-Push-WebSocket#16]
As you know, `pcntl_*` functions have limitation to use. for example:

1) Does not support in windows OS.
2) Does not enable by default and must recompile PHP.
3) Does not work in PHP as Apache module.
4) Does not work in Web and just run on CLI.
5) This function normally disabled in `php.ini` for security reason.

[ref](http://php.net/manual/en/pcntl.installation.php)

Is it possible that you do not use `pcntl_fork` and use else?

**Comment by abbychau** [comment]
actually it is not possible in this implementation. 
and in most websocket implementations for php, they need a separated php process so to keep memory managed. They should be hard to modified to work as Apache module as well.

the fundamental limitation of php_fpm and mod_php is they controlled the lifetime of php and prevented threading. If you really want a full solution then you'd better to go for ratchet, swoole or workerman.

**Comment by srchea** [comment]
Agreed with @abbychau.
Another solution would be to use Docker using a linux-based image to run your app.
